on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: HeadFox/automerge-dependabot@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
